<a href="https://colab.research.google.com/github/Aarya-Musale/Python/blob/main/Day19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

In [1]:
import numpy as np

In [3]:
#1D numpy array
a = np.array([20,10,99,30,100])
a

array([ 20,  10,  99,  30, 100])

In [4]:
np

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>

In [5]:
np.__version__

'2.0.2'

In [6]:
a

array([ 20,  10,  99,  30, 100])

In [7]:
#find max number
a.max()

np.int64(100)

In [11]:
#find min number
print(a.min())

10


In [9]:
#How many elements present?
a.size

5

In [10]:
#dimensions
a.ndim

1

In [12]:
type(a)

numpy.ndarray

In [ ]:
#Que: What is type of Numpy array?
#---> ndarray(n dimensional array)

In [13]:
b = np.array([[10,20,1],
              [-1,5,9],
              [7,40,2]])
b

array([[10, 20,  1],
       [-1,  5,  9],
       [ 7, 40,  2]])

In [14]:
b.ndim

2

In [15]:
# to check number of rows and columns
b.shape  #(rows,columns)

(3, 3)

In [16]:
# addition of all elements

print(b.sum())

93


In [17]:
# Column wise addition
print(b.sum(axis=0))

[16 65 12]


In [18]:
# Row wise addition
print(b.sum(axis=1))

[31 13 49]


In [ ]:
# Assignment: b.min(),b.max(),b.mean(),b.std() row and column wise

**Different ways of creating numpy arrays**

In [19]:
# numpy array with random numbers

np.random.random(5)

array([0.86806801, 0.53021895, 0.43190837, 0.13046085, 0.61749559])

In [21]:
np.random.random((5,3))

array([[0.37367862, 0.21613675, 0.82471714],
       [0.43090144, 0.52095057, 0.13351394],
       [0.24723002, 0.88942861, 0.9330243 ],
       [0.46329634, 0.72654352, 0.89003684],
       [0.57910799, 0.90769374, 0.56540888]])

In [22]:
# 3D array
# (Block, Rows, Columns)

np.random.random((2,2,2))

array([[[0.698937  , 0.31715632],
        [0.59506047, 0.23494607]],

       [[0.44073211, 0.40795173],
        [0.02364179, 0.60612681]]])

In [23]:
np.random

<module 'numpy.random' from '/usr/local/lib/python3.12/dist-packages/numpy/random/__init__.py'>

In [24]:
# Generate array with sequence of numbers

c = np.arange(24)  # arange:array range
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
c.size

24

In [34]:
# Convert from 1D to 2D

# use reshape() which is Temporary

print(c.reshape((6,4)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [33]:
print(c.reshape((6,2)))

ValueError: cannot reshape array of size 24 into shape (6,2)

In [35]:
# use resize() which is permanant

c.resize((3,8))

In [36]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [38]:
c.shape

(3, 8)

In [ ]:
# Convert nD to 1D ---> use ravel() which is temporary

In [39]:
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [40]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])